services:
  finance-news-agent:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/finance-news-agent
    working_dir: /finance-news-agent
    tty: true
    stdin_open: true